# Generated by Django 5.2.15 on 2026-07-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_attending', models.BooleanField(default=False, verbose_name='Attending?')),
                ('number_of_guests', models.IntegerField(default=1, verbose_name='Total in Party')),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
