# Generated by Django 5.2.15 on 2026-08-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='table_number',
            field=models.IntegerField(default=0),
        ),
    ]
